### ISSUE TITLE
Function clause in socket_loop

### ISSUE THREAD

**Issue by yrashk** [ostinelli/misultin#16]
=ERROR REPORT==== 9-Apr-2011::10:50:05 ===
Error in process <0.791.0> with exit value: {function_clause,[{misultin_http,convert_to_binary,[{http_request,'GET',{abs_path,"/extjs/resources/themes/images/default/form/exclamation.gif"},{1,1}}]},{misultin_http,socket_loop,3},{misultin_http,handle_get,2},{misultin_http... 

Not sure what exactly is happening. Will try investigating deeper later tonight (may be it is my fault somehow?)

**Comment by ostinelli** [comment]
can't tell much from this. it looks like you're using Request uri which cannot get converted to binary. Req:get(uri) returns the tuple {UriType, Uri}, maybe you need just the uri, which can be obtained with Req:get(uri_unquoted)?

**Comment by ostinelli** [comment]
got the point thanks to our discussion on #erlounge. this is due to a conflict between supporting long polling requests and http pipelining. will solve this as discussed by adding the setting of a tcp_closed detection as a request option.

**Comment by ostinelli** [comment]
added support for comet & http pipelining, by introducing the {comet, true|false} option in individual requests.
