### ISSUE TITLE
Support for PUT/DELETE

### ISSUE THREAD

**Issue by hyperthunk** [ostinelli/misultin#24]
This would be _really_ helpful.

**Comment by yrashk** [comment]
ee526fd4138bfddea48b02510309db4bfc5e9639 ?

**Comment by hyperthunk** [comment]
Ah, didn't see that. Thanks for pointing it out - will update my dependencies to point to the latest HEAD revision. :)

**Comment by ostinelli** [comment]
thanks yrashk :)

not sure about that though, since in HEAD there always is a x.x -dev version. it won't take long since 0.7.1 comes out.
