### ISSUE TITLE
can't start misultin_ssl example.

### ISSUE THREAD

**Issue by yi-yuan** [ostinelli/misultin#25]
Environment: 
Erlang R14B02
Misultin 0.6.2

Reproduce:
1. make example
2. enter ebin directory
3. run "erl"
4. run "misultin_ssl:start(8443)." in erlang command line.
5. it report an error: "*\* exception exit: {error, {error, {not_started, crypto}}}"
6. run "misultin_ssl:start(8443)." again 
7. it report an error: "*\* exception exit: {error, {error, {not_started, public_key}}}"

After check the misultin.erl, i found in line152, it should be [start_application(crypto), start_application(public_key), start_application(ssl)]. 

is it right?

**Comment by ostinelli** [comment]
have you tried running this against misultin v0.7?

**Comment by yi-yuan** [comment]
yes, it's working in v0.7.
thank you!
