### ISSUE TITLE
allow binary in chunked response

### ISSUE THREAD

**Issue by normanb** [ostinelli/misultin#27]
Hi,

in multin_req:chunk/2 can a method be added with a guard

chunk(Data, ReqT) when is_binary(Data) ->
    stream([erlang:integer_to_list(erlang:iolist_size(Data), 16), "\r\n", Data, "\r\n"], ReqT);

so that binary data can be used in a chunked response, some data can cause issues with io_lib:format.

Thanks.

**Comment by ostinelli** [comment]
hi normanb, which issues are you referring to? binary can easily be integrated in iolist()

**Comment by normanb** [comment]
Hi,

currently the code in req:chunk falls through to

chunk(Template, Vars, ReqT) ->
    Data = io_lib:format(Template, Vars),
    stream([erlang:integer_to_list(erlang:iolist_size(Data), 16), "\r\n", Data, "\r\n"], ReqT).

io_lib:format will fail for some binaries in the Template variable (at least it does with me) since Vars is usually [] as it is called from chunk/2.

chunk(Template, ReqT) ->
    chunk(Template, [], ReqT).

and if the binary contains '~' then you get an error.

I am using  Req:chunk(Data) to chunk data back to the client as the server generates it, Data is a binary.

thanks,

Norman

Norman

**Comment by ostinelli** [comment]
solved, pushed. thank you.
