### ISSUE TITLE
misultin 0.7.1 {autoexit, false} not work

### ISSUE THREAD

**Issue by viplifes** [ostinelli/misultin#28]
there are no records for disabled clients in  log file.

**Comment by ostinelli** [comment]
what are 'disabled clients'? what doesn't 'work'?

again, vipflis: this is not helpful. please provide all information to firstly understand what you report, then, to reproduce the error you are reporting, and all additional data that may be needed. Otherwise, i simply can't proceed.

**Comment by viplifes** [comment]
Sorry,I do not have a new option: Req:options([{comet, true}])

thanks, problem resolved
