### ISSUE TITLE
It seems that 'POST' does not work.

### ISSUE THREAD

**Issue by stepankuzmin** [ostinelli/misultin#31]
Hi!
I've clone repo, compile sources and copy misultin to my erlang library.
I've tested installation with misultin_hello_world example, and it works.
Then I tried to extend REST example with POST, and it dont work.
After that, I tried echo example, what build with POST in it, and POST don't work too.

My handle function:

``` erlang
handle_http(Req) ->                                                                              
io:format("METHOD: ~s~n", [Req:get(method)]),
Req:ok("").
```

Then I start misultin server, I tried such queries with curl:
stepan@stepan ~/work $ curl -X GET localhost:8080
stepan@stepan ~/work $ curl -X POST localhost:8080
stepan@stepan ~/work $ curl -X PUT localhost:8080
stepan@stepan ~/work $ curl -X DELETE localhost:8080

And get following in erlang shell:
METHOD: GET
METHOD: DELETE

So, as I see, there is just GET and DELETE are working properly.

**Comment by stepankuzmin** [comment]
Erlang R13B04 
Linux 2.6.37-gentoo-r4

**Comment by ostinelli** [comment]
to send POST data with curl use:

`curl -d "value1=foo&value2=foo2&value3=foo3" localhost:8080`

if you run misultin_echo you will have it return:

```
<misultin_test><method>POST</method><param><name>value1</name><value>foo</value></param><param><name>value2</name><value>foo2</value></param><param><name>value3</name><value>foo3</value></param></misultin_test>
```

cannot reproduce your issue.
