### ISSUE TITLE
Socket.io support

### ISSUE THREAD

**Issue by mattupstate** [ostinelli/misultin#33]
No issue, but a feature request. It would be fantastic if misultin supported the Socket.io client side API. Its becoming quite popular for real-time JavaScript implementations lately.

**Comment by ostinelli** [comment]
you probably want to look into this, which was originally built on misultin [afaik they will support other server libs in the future]:
https://github.com/yrashk/socket.io-erlang

**Comment by mattupstate** [comment]
Right on. Thanks for the tip!
