### ISSUE TITLE
hello world broken on linux

### ISSUE THREAD

**Issue by Fiedzia** [ostinelli/misultin#36]
since commit  9ce6e549d984dad9af92 hello world does not work on ubuntu (and debian as well).

steps to reproduce:

make;
cp examples/misultin_hello_world.erl ebin
cd ebin;
erlc misultin_hello_world.erl
# run erl

shell V5.7.4  (abort with ^G)
Erlang R13B03 (erts-5.7.4) [source] [64-bit] [smp:6:6] [rq:6] [async-threads:0] [hipe] [kernel-poll:false]
1> misultin_hello_world:start(8080).
*\* exception exit: shutdown

previous versions work fine

kubuntu 11.04

**Comment by dimastty** [comment]
That is because R13B03 does not support ets option {read_concurrency,boolean()} which is implimented only in R14B. Either remove {read_concurrency, false} option from misultin_server:init or get Erlang/OTP R14B.

**Comment by Fiedzia** [comment]
Thanks, upgrading to R14 helped. Might be worth to leave a note in readme for ubuntu users.

**Comment by ostinelli** [comment]
i've just provided a patch to solve this issue. can you please try it again and tell me if it now works with R13B03 on your machine?

**Comment by dimastty** [comment]
Tested on R14A (debian squeeze x64) and R13B03 (ubuntu 11.04 x64). Works well in both cases.

**Comment by ostinelli** [comment]
perfect, thank you.
