### ISSUE TITLE
Multiple servers on same node fails

### ISSUE THREAD

**Issue by hntrmrrs** [ostinelli/misultin#38]
Following the example in the wiki (https://github.com/ostinelli/misultin/wiki/ExamplesPage) entitled "Multiple Misultin servers on same node" the second server fails to start:

https://gist.github.com/1035861

It appears that the culprit was introduced through the use of `named_table` ets tables in `misultin_server`. I can fix the issue and submit a pull request but wanted to be sure that it wasn't already in progress.

**Comment by hntrmrrs** [comment]
This is also demonstrated by simply running the example like so:

```
1> misultin_multiple_servers_custom_name:start(9001, 9002).
** exception exit: shutdown
```

**Comment by ostinelli** [comment]
hi skarab,

thank you for pointing this out. this is wht it's called v0.8-dev and i'm gradually adding tests to misultin (it's about time).

i'll provide the patch asap, unfortunately i won't be able to do so before the week of july 2nd as i'm in holiday and badly connected.

**Comment by hntrmrrs** [comment]
Cool, thanks for taking the time to look at it.

**Comment by si14** [comment]
I'm about to push a fix to this issue.

**Comment by ostinelli** [comment]
thank you, push merged and issue closed.
