### ISSUE TITLE
Streaming input: big files input or endless input

### ISSUE THREAD

**Issue by maxlapshin** [ostinelli/misultin#43]
I have two cases, that are not covered with misultin yet.

They are very, very important for me now and I think, that one of them will be important for many people.

First is big file upload. Just imagine: I want to upload BluRay disk. I can't raise memory limit, so we need just streaming input.

If I upload to Ruby on Rails application begin nginx, I would do simply thing: setup nginx to save request body to the same partition, where Rails store files, than Rails will get just local path.

But it is not what I want from misultin, because I have other case for upload. If user upload flv file, I want to be able to stream it from the very beginning. So, I need to have streaming input interface.

The same streaming input can be used for endless input streams.

I will try to make a fork and add proper patch, but if you have any ideas about best architecture, it would be great.

**Comment by ostinelli** [comment]
basically you are asking to have an option for misultin to _not_ parse automatically the body, and have a way to do so actively? if this is the case, this option is already under consideration.

**Comment by jbrisbin** [comment]
I would like to be able to do this as well (handle chunked uploads) for processing large files over HTTP. Any idea when this functionality can be implemented in misultin?

**Comment by ostinelli** [comment]
hi,

i've been busy in implementing quite some features and this request has been temporarily put aside.

i believe the best way to do so is what i suggested here above, i.e. have an option for misultin to not parse the body automatically, and therefore allow a way to gradually receive the content body.

would this do for the both of you?

**Comment by jbrisbin** [comment]
I think that would work fine. I'd like to be able to handle large files (>100MB, 1GB, etc...) and I can't do that with misultin until something like this is implemented.

**Comment by ostinelli** [comment]
indeed. i will look asap into this.

**Comment by cloudhead** [comment]
+1

**Comment by ostinelli** [comment]
@maxlapshin, @jbrisbin, @cloudhead: the feature requested is now in master head.

example usage here: https://github.com/ostinelli/misultin/blob/master/examples/misultin_body_recv.erl

please let me know asap if this fits your needs / bugs, etc.

thank  you,

r.

**Comment by jbrisbin** [comment]
Thanks for letting me know! :) 

I'll try it out... 

Thanks! 

Jon Brisbin 
http//jbrisbin.com 

----- Original Message -----

**Comment by ostinelli** [comment]
issue closed.
