### ISSUE TITLE
binary support

### ISSUE THREAD

**Issue by benbro** [ostinelli/misultin#44]
I've ported most of mochiweb to work with binaries:
https://github.com/benbro/mochiweb

The following modules are the binary version of lists:
mochiweb_binary_request.erl
mochiweb_binary_cookies.erl
mochiweb_binary_headers.erl
mochiweb_binary_util.erl

I think that the only thing missing is headers but it shouldn't be too hard.
Is there a chance this functionality will be implemented in misultin?

Thanks

**Comment by ostinelli** [comment]
hi benbro, misultin is set to use list and do not plan right now to support both binaries and lists.

thank you for your feedback, will keep it in mind.
