### ISSUE TITLE
LoopPid process doesn't exit when socket is closed

### ISSUE THREAD

**Issue by maxlapshin** [ostinelli/misultin#45]
When HTTP socket is closed and misultin_socket:send is closing with exit(normal),
then LoopPid, created in misultin_http:call_mfa doesn't exit because link mechanism doesn't propagate normal exit.

The only good idea to handle with it is to start both processes under same supervisor so, that he will shutdown both of them.

**Comment by ostinelli** [comment]
i've actually another approach to this, simply put a tcp error while sending now causes an exit(kill) instead. will push asap.

thank you,

r.
