### ISSUE TITLE
make not working with R13B04

### ISSUE THREAD

**Issue by reverendpaco** [ostinelli/misultin#46]
It seems to work fine with R14B03 on my mac, but on my centos machine:

[deklund@internal misultin]$ make
/usr/local/bin/erlc -W -I include -o ebin src/_.erl
src/misultin_acceptor.erl:85: referring to built-in type tid as a remote type; please take out the module name
src/misultin_acceptor.erl:149: referring to built-in type tid as a remote type; please take out the module name
src/misultin_acceptor.erl:168: referring to built-in type tid as a remote type; please take out the module name
make: *_\* [all] Error 1

**Comment by ostinelli** [comment]
hi, have you tried modifying the suggested lines as specified?

i.e. turn the ets:tid() into tid() only?

**Comment by stepankuzmin** [comment]
I've test misultin with R13B04.

It compiles and works after replacing ets:tid to tid.
`sed -i 's/ets:tid/tid/g' src/*.erl`

**Comment by reverendpaco** [comment]
sorry... yes, the removal of the module worked for me... thanks for that
