### ISSUE TITLE
WebSocket version hybi-07 & hybi-10 support

### ISSUE THREAD

**Issue by viplifes** [ostinelli/misultin#48]
Will the added support for these versions of the websocket protocol?
Firefox 6 will support hybi-07.
Firefox 7 and Google Chrome 14 will support hybi-10.
thanks.

**Comment by sendtopms** [comment]
Chrome 14  dev is out with hybi-10

**Comment by ostinelli** [comment]
i'm currently waiting for something which looks v1.0 on websockets. keeping pace under all these protocol experiments is getting tiring.

might consider it though, are you planning to submit a patch?

**Comment by viplifes** [comment]
Yes, of course. We will try to write a patch.

**Comment by ostinelli** [comment]
i'm currently working on it, please bear with me i'm in greece right now and it might take some time.

**Comment by ostinelli** [comment]
hybi-10 is now supported in 0.8.1-dev, feedback welcome:

https://github.com/ostinelli/misultin/tree/dev

r.

**Comment by viplifes** [comment]
Thanks, I tested it in chrome 14, everything works fine!

**Comment by ostinelli** [comment]
yes, however it is still not complete.

cheers,

r.
