### ISSUE TITLE
how to handle HTTP Redirect in misultin?

### ISSUE THREAD

**Issue by barakath** [ostinelli/misultin#51]
Hi,

I am trying to redirect the request to a new destination URL. But it is not working.

I am using 

[302,"http://github.com"]

can anyone please help me with this issue

**Comment by ostinelli** [comment]
I would be surprised if that did work. :)

http://en.wikipedia.org/wiki/HTTP_302

you need to add the Location header to your response. Something like:

```
Req:respond(302, [{'Location', "http://github.com"}], "").
```

r.

**Comment by barakath** [comment]
Thanks. It works.

**Comment by ostinelli** [comment]
added a shortcut 309df57fbeaac7a954c0facda2e0f529a94bb75f
