### ISSUE TITLE
About Comet Long Polling

### ISSUE THREAD

**Issue by Jasson** [ostinelli/misultin#53]
I test misultin_comet_long_polling moule with 4 clients. I want eche client take 5s. But I found the last client take 20s. Why? It is not  Parallel?

Please reply me,Ths.

**Comment by ostinelli** [comment]
yes, it is running in different processes.

however, you are probably running the code from the same browser, thus it is running in the same process because it is being called on the same socket.

run the example from two different browsers and it should work.

r.

**Comment by Jasson** [comment]
thanks, you are rgiht. two different browsers it dose work.
Why is there  same process called the same socket in  implemenation. Maybe one request one proces,one proces one socke.
Thanks  your reply again.

**Comment by ostinelli** [comment]
i am not sure about that. if anyone pops in with an explanation, it would be good.

i would anyway recommend the hidden iframe technique instead, since the long polling method actually is still polling from the server.

**Comment by Jasson** [comment]
ostinelli  Thank you.
