### ISSUE TITLE
Firefox 7 websockets (HTTP Header)

### ISSUE THREAD

**Issue by egobrain** [ostinelli/misultin#54]
There is problem with header check function
it can't valid header in Firefox 7 because of this line in header.
The problem is because of multiple parameters, split by ","
{'Connection',"keep-alive, Upgrade"},
I created simple patch to solve this problem https://gist.github.com/1180310

**Comment by ostinelli** [comment]
can't merge as is, got your point. will add asap.

**Comment by ostinelli** [comment]
closed, thank you 85396903a2a00db9797fae4961aa1f86e0ef6272
