### ISSUE TITLE
fresh pull won't "make"

### ISSUE THREAD

**Issue by swecker** [ostinelli/misultin#55]
I have a project that uses misultin, and I'm getting things set up on a new machine and I can't get misultin going.
Once I've pulled the source and run make I get these two errors:

src/../include/misultin.hrl:69: type gen_proplist() undefined
src/../include/misultin.hrl:122: type date_tuple() undefined

and looking through that file I found that if I move the lines that define those types before they are called than the compiler gets passed this and now gives the following errors:

src/misultin_acceptor.erl:85: referring to built-in type tid as a remote type; please take out the module name
src/misultin_acceptor.erl:149: referring to built-in type tid as a remote type; please take out the module name
src/misultin_acceptor.erl:168: referring to built-in type tid as a remote type; please take out the module name

So I followed the directions on this ticket: https://github.com/ostinelli/misultin/issues/46 and the compiler moves on to the following errors:

src/misultin_http.erl:48: type socket() undefined
src/misultin_http.erl:49: type socketmode() undefined

I ran out of ideas here.  I haven't seen anyone else posting about these issues so maybe my problem lies elsewhere... Any ideas?

**Comment by ostinelli** [comment]
all the issues you are reporting relate to specs. it seems you are using old erlang versions, the otp team strongly recommends updating to latest versions, and you shouldn't see these anymore.

is this the case? otherwise please expand on your system specs and we try to work this out.

**Comment by swecker** [comment]
That was indeed the case.  I guess it's pretty naive to think that ubuntu's pre-installed erlang would be up to date, I was running Release R13B01.  I updated it and misultin works as normal now.
Thank you.
