### ISSUE TITLE
Add custom Content-Types

### ISSUE THREAD

**Issue by sinnus** [ostinelli/misultin#63]
Content-Types by extension is hard coded in misultin_utility:get_content_type. How about customization of the function?

**Comment by ostinelli** [comment]
What kind of customization would you need?

**Comment by sinnus** [comment]
I have tried to send 'crossdomain.xml' file using misultin:file but faced with restriction that I can't set Content-Type for xml files without recompiling of misultin_utility. I can offer to add option for mшsultin like {content_types, ["xml", "text/xml"]} or something else.

**Comment by ostinelli** [comment]
The best way to proceed is to do a pull request with the changes needed, so that all mimetypes get correctly covered.

The DEV branch has now what you need: 17bc2196a6544aa486c1bfd4ff7bf29cec2924dd

Thank you,

r.
