### ISSUE TITLE
Use timeout in gen_tcp:accept

### ISSUE THREAD

**Issue by knutin** [ostinelli/misultin#66]
Hi,

It would be very useful to have misultin_socket:accept/2 timeout after a few seconds if it does not accept anything, as it would allow smoother code upgrades. When it timeouts, it should re-enter the same loop with a fully qualified module name so it gets the new code. This lets us avoid killing processes to force them to get the new code and not loose any requests.

**Comment by ostinelli** [comment]
thank you for this suggestion. still not comfortable in timing these out. any system hooks you are aware of that could be used for callbacks instead?

**Comment by knutin** [comment]
Do you mean callbacks for reloading? If you are using gen-based servers and releases, there is the code_change callback, but as the process is waiting on accept/2 it is blocking these calls.

The only way I can think of is to timeout and loop. May I ask why you are uncomfortable with the timeouts?

**Comment by ostinelli** [comment]
no particular reason. i'd prefer though to have somewhat these processes reloaded on a code_change, unfortunately they depend on a supervisor which hasn't such a callback. that's why i asked for (maybe) system callbacks.

if i can't find anything else, i'll take your suggestion and implement it asap.

thank you,

r.

**Comment by ostinelli** [comment]
closed, 65952faf17c6fc8b3e292131e62b3176409f268a

please let me know if this solves your needs.

thank you,

r.

**Comment by ostinelli** [comment]
unfortunately this does not work. somehow, causing the acceptors to timeout and forcing code reload actually makes the supervisors restart the acceptors. obviously, after the 5th time the supervisors have to do this, they take down misultin as a whole.

took this away for now. if you feel like digging into it, let me know 596bb3322ca4302f734c2f1757b8ecc5810c1319

thank you,

r.

**Comment by ostinelli** [comment]
only thing that i can do to make it properly work for now is committed on 66ef7c100f67be9e1d7b06cf683171bf42c714cd

if you need you need more than that, do not hesitate to let me know and discuss how to implement this.

thank you,

r.
