### ISSUE TITLE
Ensure compatability with rev 8 of websockets

### ISSUE THREAD

**Issue by moxford** [ostinelli/misultin#67]
Firefox 7 and Aurora are using Rev8 of the draft, which does not appear to work with Misultin.

**Comment by rvirding** [comment]
I wonder if the latest version of Chrome, 15.0.874.106, is also using Rev8 as I can not get websockets and misultin to work together with it. I am running the misultin examples straight of. I just get the message in the browser "websocket was closed".

If this updated will it be possible to run both versions?

**Comment by moxford** [comment]
Chrome works on this macbook (10.0.648.151, not latest) but not on my
windows machine where it has been updated.
It looks like he's got some work in his dev-branch but not pushed to master.
Hopefully it happens, or I'll have to replace Misultin ... but I
really like the way Misultin handles the requests.  =/

-mox

On Tue, Nov 8, 2011 at 6:36 AM, Robert Virding
reply@reply.github.com
wrote:

**Comment by rvirding** [comment]
I have done some initial tests with the dev-branch and it seems to work with the latest version of Chrome. At least for my simple app. It also works with a Safari which I have purposely NOT upgraded. The "old" misultin works with this Safari so it seems to be able to handle both old and new websockets.

My usage is very basic, https://github.com/rvirding/chat_demo, and I have no idea if everything works. I too like the way misultin works, very simple, basic and straight-forward.

**Comment by ostinelli** [comment]
updated to latest version hybi-17 thanks to @rj. still some work to do on firefox.
