### ISSUE TITLE
Add inets in deps

### ISSUE THREAD

**Issue by greggy** [ostinelli/misultin#70]
Hello!

We use misultin-0.8 in our project and decided to generate release using rebar. We got:

 =CRASH REPORT==== 7-Nov-2011::15:58:08 ===
  crasher:
    initial call: misultin_server:init/1
    pid: <0.57.0>
    registered_name: []
    exception exit: {undef,[{httpd_util,rfc1123_date,[]},
                            {misultin_server,update_rfc_date,1},
                            {misultin_server,init,1},
                            {gen_server,init_it,6},
                            {proc_lib,init_p_do_apply,3}]}
      in function  gen_server:init_it/6
    ancestors: [misultin,disp_sup,<0.49.0>]
...

Please, add inets into dependents!

**Comment by ostinelli** [comment]
hi greggy,

can you please provide a patch for the DEV branch?

**Comment by greggy** [comment]
Yes, will do soon...

**Comment by greggy** [comment]
As I see misultin use a couple of functions from inets module httpd_utils. I wrote simple patch to add inets in deps https://gist.github.com/1362002 , but it was the easiest way. Maybe it will be better to add those functions into misultin? :)

**Comment by ostinelli** [comment]
i'' probably add inets as a dependency, unless you have specific reasons to suggest me not to ^^_

**Comment by ostinelli** [comment]
closed, d603d0c8e07e757f13bd82ed650af7e08ae35f97
