### ISSUE TITLE
Nameless misultin start

### ISSUE THREAD

**Issue by yrashk** [ostinelli/misultin#8]
It would be nice to have a nameless misultin start function, as start_link currently registers misultin's name which will effectively prevent us from starting multiple instances of it. Would you accept a patch that changes that? 

https://github.com/ostinelli/misultin/blob/master/src/misultin.erl#L75

**Comment by ostinelli** [comment]
this could be done only insuring backwards compatibility.

**Comment by ostinelli** [comment]
issue stays open as enhancement request.

**Comment by ostinelli** [comment]
Pushed, thank you.
