### ISSUE TITLE
BUG with ?MODULE

### ISSUE THREAD

**Issue by egobrain** [ostinelli/misultin#87]
It's me again.
You've got a mistake in misultin_http and misultin_accepter.
When you replaced function such as **accept/8** by **?MODULE:**accept/8. 
You need to export them.
in **misultin_acceptor** -export([**acceptor/8**]).
in **misultin_http** -export([**request/2**]).

Thank you :)

**Comment by nordenmark** [comment]
Issue confirmed.

Grazie!

**Comment by ostinelli** [comment]
hi,

if someone can provide this simple patch i'll be happy to merge it. i'm without my dev machine until tomorrow night. otherwise it'll be done by then.

thank you,

r.

**Comment by ostinelli** [comment]
closed, thank you 5143979e411dcebd638e8db127e1323994dab006
