### ISSUE TITLE
Error in request WebSocket and HTTPS 0.7-dev

### ISSUE THREAD

**Issue by viplifes** [ostinelli/misultin#9]
=ERROR REPORT==== 23-Mar-2011::17:05:53 ===
Error in process <0.90.0> with exit value: {undef,[{misultin_req,socket,[{misultin_req,{req,{sslsocket,new_ssl,<0.87.0>},ssl,{127,0,0,1},54668,undefined,close,undefined,{1,0},'GET',{abs_path,"/cometchat/"},"time=1300890927800",[{'Host',"site.dev"},{"X-Real-Ip","10.0.0.80"},{'X-Forwarded-For'... 

=ERROR REPORT==== 23-Mar-2011::17:06:45 ===
Error in process <0.94.0> with exit value: {undef,[{misultin_ws,socket,[{misultin_ws,{ws,{sslsocket,new_ssl,<0.91.0>},ssl,false,{10,0,0,80},44866,undefined,{'draft-hixie',76},"https://site.dev","site.dev:8333","/manager",[{'Upgrade',"WebSocket"},{'Connection',"Upgrade"},{'Host'...

**Comment by ostinelli** [comment]
hi vipflies,

please provide full information on how to reproduce the error, which includes your code, OTP version, and such.

**Comment by viplifes** [comment]
Sorry, it's my fault

**Comment by ostinelli** [comment]
which means this is an invalid issue?

**Comment by viplifes** [comment]
Yes, Sorry.
