### ISSUE TITLE
Cannot compile it with make

### ISSUE THREAD

**Issue by josevalim** [ostinelli/misultin#90]
Misultin says in the README we can simply compile it with `make` but it has a dependency on rebar which is not bundled with the repository. Or rebar should be bundled with the repo or we should change the README to make the dependency explicit. Thanks for the great project!

**Comment by ostinelli** [comment]
will do!

**Comment by ostinelli** [comment]
fixed aeb2bc2cba9f9dbd5bfb08f226cca157fe7c3c6a
