### ISSUE TITLE
How to handle to multiple content_types in one url?

### ISSUE THREAD

**Issue by leiwan5** [ostinelli/misultin#91]
as respond_to in rails does?

**Comment by ostinelli** [comment]
Send headers like this. For HTML:

``` erlang

Req:ok([{"Content-Type", "text/html"}], "<b>hello</b>").
```

For Text:

``` erlang

Req:ok([{"Content-Type", "text/plain"}], "hello").
```

This is well documented, please read the documentation and the examples, I can scarcely see this as an 'issue'. :)

r.

**Comment by leiwan5** [comment]
Sorry, I didn't describe it clearly.
For example, $.get('/users', function(){}) is expected to get an html page with users list, and $.get('/users', function(){}, 'json') a json string.
I know how to response different content-types. I want to know if there is an easy way to know what content-type the client want, or I can only parse the request header myself? or use different urls in the client, like '/users.html' and '/users.json'?
