### ISSUE TITLE
Improve README to avoid copying

### ISSUE THREAD

**Issue by ngocdaothanh** [ostinelli/misultin#95]
README says:

If you did not proceed with step 2, copy the file misultin_hello_world.erl from the
Misultin examples directory to the directory where the .beam files compiled in step 1
are located, then CD to this directory and start an Erlang shell.

To avoid copying misultin_hello_world.erl, "-pa" can be used like this:

cd examples
erl -pa ../ebin
c(misultin_hello_world).

**Comment by ostinelli** [comment]
fixed 043501458166f2e5e4a4296312dca767c9218a9d
